version: 1.0.{build}
environment:
  MINICONDA: C:\Environment\miniconda3
  NAME: python37
  ARTIFACT: '%NAME%.7z'
  PYTHON: 3.7

install:
  - curl -fsSL -o miniconda3.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
  - miniconda3.exe /S /D=%MINICONDA%
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

build_script:
  - conda create -n %NAME% python=%PYTHON% -y
  - activate %NAME%

  # - conda install -y -c conda-forge jupyterlab
  # - conda install -y -c pytorch pytorch torchvision cpuonly
  # - conda install -y scikit-learn pandas
  - pip install numpy scipy matplotlib sympy cesium scikit-learn jupyterlab pandas

  - 7z a %ARTIFACT% %MINICONDA%\envs

test: off
artifacts:
- path: '%ARTIFACT%'