version: 1.0.{build}

image: Ubuntu2004

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc make pkg-config git bison flex libelf-dev libssl-dev libncurses5-dev bc

before_build:
  - wget https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
  - tar -xJf gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz

  - wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.1.25.tar.xz
  - tar -xJf linux-4.1.25.tar.xz

  - export PATH=$(pwd)/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/bin:$PATH

build_script:
  - cd $APPVEYOR_BUILD_FOLDER/linux-4.1.25

  - make ARCH=arm64 defconfig
  - make ARCH=arm64 KCONFIG_ALLCONFIG=.config allnoconfig

  - sed -i "s/YYLTYPE yylloc;/extern YYLTYPE yylloc;/" scripts/dtc/dtc-lexer.lex.c_shipped

  - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare
  - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- scripts

  # - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/usb/class CONFIG_USB_PRINTER=m modules
  - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/usb/class CONFIG_USB_PRINTER=m INSTALL_MOD_PATH=$APPVEYOR_BUILD_FOLDER/modules modules_install

  - cd $APPVEYOR_BUILD_FOLDER/hello

  - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

test: off
artifacts:
- path: modules
  name: modules
