version: 1.0.{build}
image: Ubuntu2004

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc make pkg-config git bison flex libelf-dev libssl-dev libncurses5-dev bc libarchive-tools

before_build:
  - wget https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/arm-linux-gnueabihf/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz
  - tar -xJf gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz

  - wget http://ftp.porcupine.org/pub/security/tcp_wrappers_7.6.tar.gz
  - tar -xzf tcp_wrappers_7.6.tar.gz

  - wget https://github.com/kenyapcomau/p910nd/archive/0.97/p910nd-0.97.tar.gz
  - tar -xzf p910nd-0.97.tar.gz

  - export PATH=$(pwd)/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf/bin:$PATH

build_script:
  - cd $APPVEYOR_BUILD_FOLDER/p910nd-0.97
  - make USE_WRAP=1

test: off
artifacts:
- path: p910nd-0.97
  name: p910nd-0.97
