version: 1.0.{build}
environment:
  MINICONDA: C:\Environment\miniconda3
  NAME: prophet
  ARTIFACT: '%NAME%.7z'
  PYTHON: 3.7

install:
  - curl -fsSL -o miniconda3.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
  - miniconda3.exe /S /D=%MINICONDA%
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

build_script:
  - conda create -n %NAME% python=%PYTHON% -y
  - activate %NAME%

  - conda install libpython m2w64-toolchain_win-64 -y
  - ps: |
      Set-Content -Path "$env:MINICONDA\envs\$env:NAME\Lib\distutils\distutils.cfg" -Value @"
      [build]
      compiler=mingw32
      
      [build_ext]
      compiler=mingw32
      "@

  # This order is required
  - pip install pystan
  - pip install convertdate
  - pip install pandas lunarcalendar holidays
  - pip install fbprophet

  # It can be installed by one command
  # - conda install -c conda-forge fbprophet -y

  - 7z a %ARTIFACT% %MINICONDA%\envs

test: off
artifacts:
- path: '%ARTIFACT%'