version: 1.0.{build}
environment:
  MINICONDA: C:\Environment\miniconda3
  NAME: prophet
  PYTHON: 3.7
  ARTIFACT: '%NAME%.7z'

install:
  - curl -fsSL -o miniconda3.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
  - miniconda3.exe /S /D=%MINICONDA%
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

build_script:
  - conda create -n %NAME% python=%PYTHON% -y
  - activate %NAME%

  - conda install libpython -y
  # This order is required
  - pip install pystan
  - pip install convertdate
  - pip install pandas lunarcalendar holidays
  - pip install fbprophet

  - 7z a %ARTIFACT% %MINICONDA%\envs

test: off
artifacts:
- path: '%ARTIFACT%'
