version: 1.0.{build}

image: Ubuntu2004

environment:
  NDK_VERSION: r25c
  API_LEVEL: 23

  SELINUX_VERSION: 3.2
  BSDTAR_VERSION: 3.6.2
  PCRE_VERSION: 8.44
  TAR_VERSION: 1.34
  # SETOOLS3_VERSION: master

install:
  - curl -fsSL https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -o android-ndk.zip
  - unzip -q android-ndk.zip

  - export NDK_HOME=$(pwd)/android-ndk-$NDK_VERSION
  - export PATH=$NDK_HOME/prebuilt/linux-x86_64/bin:$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

  - export CC=aarch64-linux-android$API_LEVEL-clang
  - export CXX=aarch64-linux-android$API_LEVEL-clang
  - export AR=llvm-ar
  - export RANLIB=llvm-ranlib

before_build:
  - curl -fsSL https://github.com/libarchive/libarchive/releases/download/v$BSDTAR_VERSION/libarchive-$BSDTAR_VERSION.tar.gz -o bsdtar.tar.gz
  - tar xzf bsdtar.tar.gz

  - curl -fsSL https://downloads.sourceforge.net/project/pcre/pcre/$PCRE_VERSION/pcre-$PCRE_VERSION.tar.gz -o pcre.tar.gz
  - tar xzf pcre.tar.gz

  - curl -fsSL https://github.com/SELinuxProject/selinux/releases/download/$SELINUX_VERSION/libsepol-$SELINUX_VERSION.tar.gz -o libsepol.tar.gz
  - tar xzf libsepol.tar.gz

  - curl -fsSL https://github.com/SELinuxProject/selinux/releases/download/$SELINUX_VERSION/libselinux-$SELINUX_VERSION.tar.gz -o libselinux.tar.gz
  - tar xzf libselinux.tar.gz

  - curl -fsSL https://github.com/termux/termux-packages/raw/master/packages/libandroid-glob/glob.c --create-dirs -o libandroid-glob/glob.c
  - curl -fsSL https://github.com/termux/termux-packages/raw/master/packages/libandroid-glob/glob.h --create-dirs -o libandroid-glob/glob.h

  - curl -fsSL https://mirrors.kernel.org/gnu/tar/tar-$TAR_VERSION.tar.gz -o tar.tar.gz
  - tar xzf tar.tar.gz

  # - curl -fsSL https://github.com/TresysTechnology/setools3/archive/refs/heads/$SETOOLS3_VERSION.tar.gz -o setools3.tar.gz
  # - tar xzf setools3.tar.gz

build_script:
  # bsdtar
  - pushd libarchive-$BSDTAR_VERSION
  - sed -i "s/return \"\"/return \"UTF-8\"/g" libarchive/archive_string.c
  - ./configure CFLAGS="-Icontrib/android/include" --host=aarch64-linux-android
                                                   --prefix=$APPVEYOR_BUILD_FOLDER/build
                                                   --without-xml2
  - make V=1 install
  - popd

  # pcre
  - pushd pcre-$PCRE_VERSION
  - ./configure LDFLAGS="-lstdc++" --host=aarch64-linux-android
                                   --prefix=$APPVEYOR_BUILD_FOLDER/build
  - make install
  - popd

  # libsepol
  - pushd libsepol-$SELINUX_VERSION
  - make DISABLE_CIL="y"
         DESTDIR="$APPVEYOR_BUILD_FOLDER/build"
         install
  - popd

  # libselinux
  - pushd libselinux-$SELINUX_VERSION
  - sed -i 's/freecon\.c/freecon.c setfilecon.c lsetfilecon.c fsetfilecon.c getfilecon.c lgetfilecon.c fgetfilecon.c/g' src/Makefile
  - make CFLAGS="-I$APPVEYOR_BUILD_FOLDER/build/include -I$APPVEYOR_BUILD_FOLDER/build/usr/include" USE_PCRE2="n"
         LDFLAGS="-L$APPVEYOR_BUILD_FOLDER/build/lib -L$APPVEYOR_BUILD_FOLDER/build/usr/lib"        ANDROID_HOST="y"
                                                                                                    DESTDIR="$APPVEYOR_BUILD_FOLDER/build"
         install
  - popd

  # libandroid-glob
  - pushd libandroid-glob
  - $CC -I. -c glob.c
  - $AR rcu libandroid-glob.a glob.o
  - cp glob.h $APPVEYOR_BUILD_FOLDER/build/include/
  - cp libandroid-glob.a $APPVEYOR_BUILD_FOLDER/build/lib/
  - popd

  # tar
  - pushd tar-$TAR_VERSION
  - ./configure CFLAGS="-I$APPVEYOR_BUILD_FOLDER/build/include -I$APPVEYOR_BUILD_FOLDER/build/usr/include"                     --host=aarch64-linux-android
                LDFLAGS="$APPVEYOR_BUILD_FOLDER/build/lib/libandroid-glob.a $APPVEYOR_BUILD_FOLDER/build/usr/lib/libselinux.a" --prefix=$APPVEYOR_BUILD_FOLDER/build
                                                                                                                               --with-selinux
  - make install
  - popd

  # setools3
  # - pushd setools3-master
  # - autoreconf -i -s
  # - ./configure --host=aarch64-linux-android CFLAGS="-L$APPVEYOR_BUILD_FOLDER/build/usr/lib"
                                             # ac_cv_header_selinux_selinux_h=yes
                                             # ac_cv_header_selinux_context_h=yes
                                             # ac_cv_lib_selinux_selinux_policy_root=yes
                                             # $(echo ac_cv_file_$APPVEYOR_BUILD_FOLDER/build/usr/lib/libsepol.a | sed 's/\W/_/g')=yes
                                             # --disable-gui
                                             # --disable-swig-tcl
                                             # --disable-swig-java
                                             # --disable-swig-python
                                             # --with-sepol-devel=$APPVEYOR_BUILD_FOLDER/build/usr
                                             # --with-selinux-devel=
  # - make install
  # - popd

test: off
artifacts:
- path: build
