language: generic

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get -y install autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils

install:
  - cd /opt
  - sudo git clone https://github.com/seven1oe/rt-n56u4p.git rt-n56u
  # - cd rt-n56u
  # - sudo git remote add rt-n56u https://github.com/andy-padavan/rt-n56u.git
  # - sudo git fetch rt-n56u
  # - sudo git merge rt-n56u/master --no-edit

script:

  - while sleep 5m; do echo -e "\n"; done &

  - cd /opt/rt-n56u/toolchain-mipsel

  - sudo ./clean_sources

  - sudo ./build_toolchain >/tmp/build.log 2>&1 || tail -100 /tmp/build.log; test $? -ne 0

  - cd /opt/rt-n56u/trunk

  - sudo ./clear_tree

  - sudo ./build_firmware >/tmp/build.log 2>&1 || tail -100 /tmp/build.log; test $? -ne 0
  
  - kill %1
