version: 1.0.{build}
build_script:
  - git clone https://github.com/sensepost/apostille.git src
  - cd src
  - mvn package -Dmaven.test.skip=true

  - 7z a ..\apostille.zip target\*.jar
test: off
artifacts:
- path: apostille.zip
