version: 1.0.{build}
build_script:
- ps: |-
    $installer = 'vs_Community.exe'
    $url = 'https://aka.ms/vs/16/release/'
    Invoke-WebRequest $url$installer -OutFile $installer
    
    $dest = 'packages'
    $arguments = @(
        '--layout',
        $dest,
        '--add',
        'Microsoft.VisualStudio.Workload.ManagedDesktop',
        '--wait',
        '--passive'
    )
    $p = Start-Process -FilePath $installer -ArgumentList $arguments -PassThru
    $p | Wait-Process
    if ($p.ExitCode -ne 0)
    {
        Write-Error "failed with code $($p.ExitCode)"
    }
    
    Get-ChildItem -Path $dest
test: off
artifacts:
- path: packages
  name: vs