version: 1.0.{build}
image: Visual Studio 2019

environment:
  ROOT: '%APPVEYOR_BUILD_FOLDER%\msys64'
  BASH: '%ROOT%\msys2_shell.cmd -defterm -no-start -mingw64 -here -c'

  OPENSSL_VERSION: 3.1.0
  STUNNEL_VERSION: 5.69

install:
  - curl -fsSL https://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz | 7z x -si -so -txz | 7z x -si -ttar
  - '%ROOT%\msys2_shell.cmd -defterm -no-start -c "uname -a"'

  - '%BASH% "pacman -Sy --noconfirm mingw-w64-x86_64-{gcc,binutils} make"' # MINGW_PACKAGE_PREFIX openssl
  - '%BASH% "ln $MSYSTEM_PREFIX/bin/windres $MSYSTEM_PREFIX/bin/$MSYSTEM_CHOST-windres"'

before_build:
  - '%BASH% "wget -q -O - https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz | tar xzf -"'
  - '%BASH% "wget -q -O - https://www.stunnel.org/downloads/stunnel-$STUNNEL_VERSION.tar.gz | tar xzf -"'

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\openssl-%OPENSSL_VERSION%
  - '%BASH% "./Configure --prefix=$MSYSTEM_PREFIX --libdir=lib shared mingw64 enable-capieng"'
  - '%BASH% "make install"'
  - '%BASH% "cp ms/applink.c $PKG_CONFIG_SYSTEM_INCLUDE_PATH/openssl/"' # !

  - cd %APPVEYOR_BUILD_FOLDER%\stunnel-%STUNNEL_VERSION%
  - '%BASH% "./configure"'
  - cd src
  - '%BASH% "sed -i ""s#-llibeay32 -lssleay32#-static -lssl -lcrypto -lws2_32 -lwsock32#g"" mingw.mk"'
  - '%BASH% "make mingw64"'

test: off
artifacts:
- path: stunnel-%STUNNEL_VERSION%\bin
  name: stunnel