version: 1.0.{build}
image: Visual Studio 2019

environment:
  ROOT: '%APPVEYOR_BUILD_FOLDER%\msys64'
  BASH: '%ROOT%\msys2_shell.cmd -defterm -no-start -here -c'

  OPENSSL_VERSION: 3.1.0 # TODO: test
  STUNNEL_VERSION: 5.69

  matrix:
    - MSYSTEM: MINGW64
      PACKAGES: make mingw-w64-x86_64-{gcc,binutils,diffutils,openssl}
      PATCH_SCRIPT: s#-llibeay32 -lssleay32#-static -lssl -lcrypto -lws2_32 -lwsock32#g; s#\$(win32_prefix)windres#windres#g
      PATCH_TARGET: mingw.mk
      TARGET: mingw64

    - MSYSTEM: MSYS # cygwin
      PACKAGES: make gcc binutils diffutils openssl-devel
      PATCH_SCRIPT: s#-lssl -lcrypto#$MSYSTEM_PREFIX/lib/libssl.a $MSYSTEM_PREFIX/lib/libcrypto.a#g; s#-avoid-version#-avoid-version -no-undefined#g
      PATCH_TARGET: Makefile
      TARGET: install

install:
  - curl -fsSL https://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz | 7z x -si -so -txz | 7z x -si -ttar

  - '%BASH% "env"'
  - '%BASH% "pacman -Sy --noconfirm %PACKAGES%"'

before_build:
  - '%BASH% "wget -q -O - https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz | tar xzf -"'
  - '%BASH% "wget -q -O - https://www.stunnel.org/downloads/stunnel-$STUNNEL_VERSION.tar.gz | tar xzf -"'

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\openssl-%OPENSSL_VERSION%
  # - '%BASH% "./Configure --prefix=$MSYSTEM_PREFIX --libdir=lib"' # Cygwin-x86_64 mingw64 enable-capieng
  # - '%BASH% "make install_sw"'
  - if %MSYSTEM%==MINGW64 %BASH% "cp ms/applink.c $MSYSTEM_PREFIX/include/openssl/"

  - cd %APPVEYOR_BUILD_FOLDER%\stunnel-%STUNNEL_VERSION%
  - '%BASH% "./configure"'
  - cd src
  - '%BASH% "sed -i ""%PATCH_SCRIPT%"" $PATCH_TARGET"'
  - '%BASH% "make $TARGET"'

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%

  - if %MSYSTEM%==MINGW64 xcopy /S stunnel-%STUNNEL_VERSION%\bin build\

  - if %MSYSTEM%==MSYS xcopy %ROOT%\usr\bin\stunnel.exe build\
  - if %MSYSTEM%==MSYS xcopy %ROOT%\usr\bin\msys-2.0.dll build\

test: off
artifacts:
- path: build
  name: stunnel
