version: 1.0.{build}

environment:
  BASH: '"C:\Program Files\Git\usr\bin\bash.exe"'

  NDK_VERSION: r22b
  ABI_VERSION: 21
  SELINUX_VERSION: 3.2

install:
  - curl -fsSL https://dl.google.com/android/repository/android-ndk-%NDK_VERSION%-windows-x86_64.zip -o android-ndk-%NDK_VERSION%-windows-x86_64.zip
  - unzip -q android-ndk-%NDK_VERSION%-windows-x86_64.zip
  - set NDK_HOME=%CD%\android-ndk-%NDK_VERSION%
  - set PATH=%NDK_HOME%\prebuilt\windows-x86_64\bin;%NDK_HOME%\toolchains\llvm\prebuilt\windows-x86_64\bin;%PATH%

  - curl -fsSL https://github.com/SELinuxProject/selinux/releases/download/%SELINUX_VERSION%/libsepol-%SELINUX_VERSION%.tar.gz -o libsepol-%SELINUX_VERSION%.tar.gz
  - tar xzf libsepol-%SELINUX_VERSION%.tar.gz

  - git clone https://bitbucket.org/joshua_brindle/sepolicy-inject.git

  - set CC=aarch64-linux-android%ABI_VERSION%-clang.cmd
  - set AR=aarch64-linux-android-ar.exe
  - set RANLIB=aarch64-linux-android-ranlib.exe

build_script:
  # libsepol
  - '%BASH% -lc "cd libsepol-%SELINUX_VERSION% &&
                 make DESTDIR=\"$(pwd)/../build\" DISABLE_CIL=\"y\" install"'

  # sepolicy-inject
  - '%BASH% -lc "cd sepolicy-inject &&
                 sed -i \"3s/\/x86_64-linux-gnu//\" Makefile &&
                 sed -i \"235s/char ch;/int ch;/\" sepolicy-inject.c"'
                 # ^ patch line 3 for `LIBDIR`
                 # ^ patch line 235 for `-Werror`

  - '%BASH% -lc "cd sepolicy-inject &&
                 make DESTDIR=\"$(pwd)/../build\""'

  - '%BASH% -lc "cp sepolicy-inject/sepolicy-inject $(pwd)/build/usr/bin"'

test: off
artifacts:
- path: build
  name: libsepol-%SELINUX_VERSION%
