version: 1.0.{build}
environment:
  MINICONDA: C:\Environment\miniconda3
  NAME: python27
  ARTIFACT: '%NAME%.7z'
  PYTHON: 2.7

install:
  - curl -fsSL -o miniconda3.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
  - miniconda3.exe /S /D=%MINICONDA%
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

build_script:
  - conda create -n %NAME% python=%PYTHON% -y
  - activate %NAME%

  - pip install pefile

  - 7z a %ARTIFACT% %MINICONDA%\envs\%NAME%

test: off
artifacts:
- path: '%ARTIFACT%'