version: 1.0.{build}
environment:
  BASH: C:\msys64\usr\bin\bash.exe
  HOME: C:\msys64\home
  MSYSTEM: MINGW64
build_script:
  - '%BASH% -lc "wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && tar -xzf ta-lib-0.4.0-src.tar.gz"'
  - '%BASH% -lc "cd ta-lib && LDFLAGS="-lm" ./configure --prefix=/home/build && make install"'
  - 7z a ta-lib.zip %HOME%\build

test: off
artifacts:
- path: ta-lib.zip