version: 1.0.{build}
image: Ubuntu2004

install:
  - sudo apt-get update --allow-releaseinfo-change
  - sudo apt-get install -y gcc make pkg-config git bison flex libelf-dev libssl-dev libncurses5-dev bc

before_build:
  - wget https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
  - tar -xJf gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz

  - wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.1.25.tar.xz
  - tar -xJf linux-4.1.25.tar.xz

  - export PATH=$(pwd)/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/bin:$PATH

build_script:
  - cd $APPVEYOR_BUILD_FOLDER/linux-4.1.25

  - export ARCH=arm64
  - export CROSS_COMPILE=aarch64-linux-gnu-

  - make defconfig
  # fix
  - sed -i "s/CONFIG_JUMP_LABEL=y/CONFIG_JUMP_LABEL=n/" .config
  - sed -i "s/# CONFIG_MODULE_SIG is not set/CONFIG_MODULE_SIG=y/" .config
  # usblp
  - sed -i "s/CONFIG_PREEMPT=y/CONFIG_PREEMPT=n/" .config
  - sed -i "s/CONFIG_UNINLINE_SPIN_UNLOCK=y/CONFIG_UNINLINE_SPIN_UNLOCK=n/" .config
  # usbip
  - sed -i "s/CONFIG_PINCTRL=y/CONFIG_PINCTRL=n/" .config
  - sed -i "s/CONFIG_DMA_CMA=y/CONFIG_DMA_CMA=n/" .config

  - make KCONFIG_ALLCONFIG=.config allnoconfig
  - make prepare

  # - sed -i "s/YYLTYPE yylloc;/extern YYLTYPE yylloc;/" scripts/dtc/dtc-lexer.lex.c_shipped
  - make CONFIG_DTC=n scripts

  - sed -i "s/\"lp%d\"/\"lp\"/" drivers/usb/class/usblp.c
  - make V=1 M=drivers/usb/class CONFIG_USB_PRINTER=m modules
  - make V=1 M=drivers/usb/class CONFIG_USB_PRINTER=m INSTALL_MOD_PATH=$APPVEYOR_BUILD_FOLDER/modules modules_install

  - make V=1 M=drivers/usb/usbip CONFIG_USBIP_CORE=m CONFIG_USBIP_HOST=m CONFIG_USBIP_DEBUG=y modules
  - make V=1 M=drivers/usb/usbip CONFIG_USBIP_CORE=m CONFIG_USBIP_HOST=m CONFIG_USBIP_DEBUG=y INSTALL_MOD_PATH=$APPVEYOR_BUILD_FOLDER/modules modules_install

  # - make V=1 M=$APPVEYOR_BUILD_FOLDER/kmod modules
  # - make V=1 M=$APPVEYOR_BUILD_FOLDER/kmod INSTALL_MOD_PATH=$APPVEYOR_BUILD_FOLDER/modules modules_install

test: off
artifacts:
- path: modules
  name: modules
